In [2]:
# data structure
import numpy
print (help(numpy.genfromtxt))

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings. The string

In [8]:
# matrix
vector = numpy.array([1, 2, 3, 4])
matrix = numpy.array([[5, 10, 15],[20, 25, 30],[5, 4, 2]]) # tip:dont forget medium bracket at the outter space 
print (vector)
print (matrix)

[1 2 3 4]
[[ 5 10 15]
 [20 25 30]
 [ 5  4  2]]


In [11]:
# use .shape to figure out the number of elements in the array
vector = numpy.array([1, 2, 3, 4])
print (vector.shape) # reture number of var in vector
# reture the row and column of matrix
matrix = numpy.array([[5, 10, 15],[20, 25, 30]])
print (matrix.shape)

(4,)
(2, 3)


In [14]:
# each value in Numpy array has to have the same data type
numbers = numpy.array([1, 2, 3, 4])
print (numbers)
numbers.dtype

numbersfloat = numpy.array([1, 2, 3, 4.0]) # automatically adjust to float
print (numbersfloat)
numbersfloat.dtype

numberstring = numpy.array([1, 2, 3, '4']) # automatically adjust to string
print (numberstring)
numberstring.dtype

[1 2 3 4]
[1. 2. 3. 4.]
['1' '2' '3' '4']


dtype('<U11')

In [16]:
weather = numpy.genfromtxt('python_MLE_3.txt', delimiter=',', dtype=str, skip_header=1)
# numpy read file
# name splite type 1/0skip first line
print (weather)

weather_chengdu = weather[2,1]
print (weather_chengdu)
city_fog = weather[1,0]
print (city_fog)

[['beijing' 'sunny']
 ['urumqi' 'fog']
 ['chengdu' 'rain']
 ['shanghai' 'sun']]
rain
urumqi


In [19]:
vector = numpy.array([2, 34, 543, 244, 54254])
print (vector[0:3])

matrix = numpy.array([[5, 10, 15],[20, 25, 30],[5, 4, 2]])
print (matrix[:,1])
print (matrix[1,2])

[  2  34 543]
[10 25  4]
30


In [21]:
# true or false
vector = numpy.array([5, 10, 15, 20])
vector == 15

matrix = numpy.array([[5, 10, 15],[20, 25, 30],[5, 4, 2]])
matrix == 15

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [22]:
# find true value
vector = numpy.array([5, 10, 15, 20])
equal_to_fifteen = (vector == 15)
print (equal_to_fifteen)
print (vector[equal_to_fifteen])

[False False  True False]
[15]


In [25]:
# comparisons 
# and/or/not 
vector = numpy.array([5, 10, 15, 20])
equal_to_ten_and_fifteen = (vector == 15) & (vector == 10)
print (equal_to_ten_and_fifteen)

equal_to_ten_or_fifteen = (vector == 15) | (vector == 10)
print (equal_to_ten_or_fifteen)

revalue_ten_or_fifteen = (vector == 15) | (vector == 10)
print (revalue_ten_or_fifteen)
vector[revalue_ten_or_fifteen] = 50
print (vector)

[False False False False]
[False  True  True False]
[False  True  True False]
[ 5 50 50 20]


In [27]:
# convert data type use ndarray.astype()
vector = numpy.array([5, 10, 15, 20])
print (vector)
print (vector.dtype)

vectorf = vector.astype(float)
print (vectorf)
print (vectorf.dtype)

[ 5 10 15 20]
int32
[ 5. 10. 15. 20.]
float64


In [30]:
# max and min
vector = numpy.array([5, 10, 15, 20])
print (vector.min())
print (vector.max())

5
20


In [35]:
# axis dictate which dimension we perform operation on
# 1 represent row/ 0 represent column
matrix = numpy.array([
                [5, 10, 15],
                [20, 25, 30],
                [5, 4, 2]
            ])
matrix_sum = matrix.sum(axis=0)
matrix_max = matrix.max(axis=1)
print (matrix_sum)
print (matrix_max)

[30 39 47]
[15 30  5]


In [45]:
import numpy as np # redefine numpy as shorthand np
print (np.arange(15)) # numpy.arange()
a = np.arange(15).reshape(3, 5) # reshape the vector to 3*5 matrix
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [46]:
a.shape # use to debug 

(3, 5)

In [47]:
a.ndim # the number of axes of the array(dimensions)

2

In [48]:
a.dtype.name 

'int32'

In [49]:
a.size # total number of element

15

In [50]:
# initialize matrix
np.zeros ((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [51]:
np.ones( (2,3,4), dtype=np.int32 )

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [53]:
# create sequences of numbers
print (np.arange( 10, 30, 5 ))
print (np.arange( 0, 2, 0.3 ))

[10 15 20 25]
[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [54]:
# create random matrix in [-1,1]
np.random.random((2,3))

array([[0.10159561, 0.74369618, 0.68706628],
       [0.87830875, 0.64191808, 0.5118338 ]])

In [55]:
# find a group of number with same gap number np.linspace(lower bound, higher  bound, N)
from numpy import pi
np.linspace( 0, 2*pi, 100 )

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

In [58]:
A = np.array( [[1,1],
              [0,1]] )
B = np.array( [[2,0], 
               [3,4]] )
print (A)
print ('-------')
print (B)
print ('-------')
print (A*B)
print ('-------')
print (A.dot(B))
print ('-------')
print (np.dot(A, B))

[[1 1]
 [0 1]]
-------
[[2 0]
 [3 4]]
-------
[[2 0]
 [0 4]]
-------
[[5 4]
 [3 4]]
-------
[[5 4]
 [3 4]]


In [2]:
# Some normal computation
import numpy as np
B = np.arange(3)
print (B)
print (np.exp(B))
print (np.sqrt(B))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [6]:
# return the floor of input (int)
a = np.floor(10*np.random.random((3,4))) # random need a small bracket inside
print (a)
print ('--------')

#reshape the matrix
print (a.ravel()) # flatten the array
print ('--------')
a.shape = (6,2) # reshape to a matrix 6*2
print (a)
print ('--------')
print (a.T) # Transpose matrix

[[0. 5. 4. 3.]
 [7. 3. 1. 2.]
 [0. 1. 2. 4.]]
--------
[0. 5. 4. 3. 7. 3. 1. 2. 0. 1. 2. 4.]
--------
[[0. 5.]
 [4. 3.]
 [7. 3.]
 [1. 2.]
 [0. 1.]
 [2. 4.]]
--------
[[0. 4. 7. 1. 0. 2.]
 [5. 3. 3. 2. 1. 4.]]


In [12]:
# Matrix splicing np.vstack(())/np.hstack(())
# row/column

a = np.floor(10*np.random.random((3,4)))
b = np.floor(10*np.random.random((3,4)))
print (a)
print ('------------')
print (b)
print ('------------')
print (np.vstack((a,b)))
print ('------------')
print (np.hstack((a,b)))

[[8. 9. 4. 2.]
 [7. 7. 2. 7.]
 [4. 3. 6. 7.]]
------------
[[9. 8. 9. 6.]
 [2. 0. 1. 6.]
 [6. 4. 1. 3.]]
------------
[[8. 9. 4. 2.]
 [7. 7. 2. 7.]
 [4. 3. 6. 7.]
 [9. 8. 9. 6.]
 [2. 0. 1. 6.]
 [6. 4. 1. 3.]]
------------
[[8. 9. 4. 2. 9. 8. 9. 6.]
 [7. 7. 2. 7. 2. 0. 1. 6.]
 [4. 3. 6. 7. 6. 4. 1. 3.]]


In [18]:
# split np.hsplit() row / np.vsplit() column
a = np.floor(10*np.random.random((3,4)))
print (a)
print ('------------')
print (np.hsplit(a,4)) # average split
print ('------------')
print (np.hsplit(a,(2,3)))
print ('------------')
print (np.vsplit(a,3))

[[7. 0. 6. 3.]
 [4. 1. 5. 3.]
 [1. 2. 0. 6.]]
------------
[array([[7.],
       [4.],
       [1.]]), array([[0.],
       [1.],
       [2.]]), array([[6.],
       [5.],
       [0.]]), array([[3.],
       [3.],
       [6.]])]
------------
[array([[7., 0.],
       [4., 1.],
       [1., 2.]]), array([[6.],
       [5.],
       [0.]]), array([[3.],
       [3.],
       [6.]])]
------------
[array([[7., 0., 6., 3.]]), array([[4., 1., 5., 3.]]), array([[1., 2., 0., 6.]])]


In [22]:
# make a b which can totally represent a 
# b=====a
# same id same value
a = np.arange(12)
b = a
print (b is a)
b.shape = 3,4
print (b)
print (a.shape)
print (id(a))
print (id(b)) # same id

True
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
(3, 4)
1803558231776
1803558231776


In [26]:
# make a b which can partly represent a 
# looks as the same data with different id
c = a.view()
print (c is a)
c.shape = 3,4
print (a.shape)
print (id(c))
print (id(a))

c[0,3] = 123452
print (a)

False
(3, 4)
1803541495120
1803558231776
[[     0      1      2 123452]
 [     4      5      6      7]
 [     8      9     10     11]]


In [30]:
# copy method 
# just copy the current value
# dont effect the future change
d = a.copy()
print (d is a)
d[0,0] = 9999
print (d)
print (a)

False
[[  9999      1      2 123452]
 [     4      5      6      7]
 [     8      9     10     11]]
[[     0      1      2 123452]
 [     4      5      6      7]
 [     8      9     10     11]]


In [33]:
# argmax
data = np.sin(np.arange(20)).reshape(5,4)
print (data)
ind = data.argmax(axis=0)
print (ind)
data_max = data[ind, range(data.shape[1])]

[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]
 [-0.53657292  0.42016704  0.99060736  0.65028784]
 [-0.28790332 -0.96139749 -0.75098725  0.14987721]]
[2 0 3 1]


array([0.98935825, 0.84147098, 0.99060736, 0.6569866 ])

In [35]:
a = np.arange(10,40,10) 
print (a)
b = np.tile(a,(4,2)) # row become four times as the original one
print (b)

[10 20 30]
[[10 20 30 10 20 30]
 [10 20 30 10 20 30]
 [10 20 30 10 20 30]
 [10 20 30 10 20 30]]


In [43]:
# sort the data set
a = np.array([[4, 3, 5],[1, 2, 1]])
print (a)
print ('------------')
b = np.sort(a, axis=1)
print (b)
a.sort(axis=1)
print ('------------')
print (a)
a = np.array([4, 3, 1, 2])
j = np.argsort(a) # index for the sort
print (j)
print ('------------')
print (a[j])

[[4 3 5]
 [1 2 1]]
------------
[[3 4 5]
 [1 1 2]]
------------
[[3 4 5]
 [1 1 2]]
[2 3 1 0]
------------
[1 2 3 4]
